Vagrant.configure("2") do |config|
  # Usa una imagen ligera de Ubuntu 22.04
  config.vm.box = "ubuntu/jammy64"
  
  # Configuración de red (accesible via IP)
  config.vm.network "private_network", ip: "192.168.56.7"

  # Montar la carpeta local en una ruta de la VM
  config.vm.synced_folder "./static_website", "/home/vagrant/static_website" 

  # Provisionamiento con Shell
  config.vm.provision "shell", inline: <<-SHELL
    echo "¡Hola desde el provisionamiento!" > /tmp/hola.txt
  SHELL

  config.vm.provision "shell", path: "scripts/instalar_nginx.sh"
  config.vm.provision "shell", path: "scripts/instalar_docker.sh"
end